version: '3.4'

services:
  creator.api:
    image: creatorapi:dev
    container_name: Creator.API
    build:
      target: base
      labels:
        com.microsoft.created-by: "visual-studio"
        com.microsoft.visual-studio.project-name: "Creator.API"
    environment:
      - DOTNET_USE_POLLING_FILE_WATCHER=1
      - ASPNETCORE_LOGGING__CONSOLE__DISABLECOLORS=true
      #- NUGET_FALLBACK_PACKAGES=$container_paths_to_fallback_packages_creator.api$
    volumes:
      - D:\All Docs\Code\Mkopa\MkopaSMSSolutions\Creator.API:/app
      - D:\All Docs\Code\Mkopa\MkopaSMSSolutions:/src
      - C:\Users\Windows10Pro\vsdbg\vs2017u5:/remote_debugger:rw
#$nuget_volume_mapping_creator.api$
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro

    entrypoint: tail -f /dev/null
    labels:
      com.microsoft.visualstudio.debuggee.program: "dotnet"
      #com.microsoft.visualstudio.debuggee.arguments: " $debuggee_arguments_probing_paths_creator.api$ \"/app/bin/Debug/netcoreapp3.1/Creator.API.dll\""
      com.microsoft.visualstudio.debuggee.workingdirectory: "/app"
      com.microsoft.visualstudio.debuggee.killprogram: "/bin/sh -c \"if PID=$$(pidof dotnet); then kill $$PID; fi\""
    tty: true
  sms.api:
    image: smsapi:dev
    container_name: SMS.API
    build:
      target: base
      labels:
        com.microsoft.created-by: "visual-studio"
        com.microsoft.visual-studio.project-name: "SMS.API"
    environment:
      - DOTNET_USE_POLLING_FILE_WATCHER=1
      - ASPNETCORE_LOGGING__CONSOLE__DISABLECOLORS=true
      #- NUGET_FALLBACK_PACKAGES=$container_paths_to_fallback_packages_sms.api$
    volumes:
      - D:\All Docs\Code\Mkopa\MkopaSMSSolutions\SMS.API:/app
      - D:\All Docs\Code\Mkopa\MkopaSMSSolutions:/src
      - C:\Users\Windows10Pro\vsdbg\vs2017u5:/remote_debugger:rw
#$nuget_volume_mapping_sms.api$
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro

    entrypoint: tail -f /dev/null
    labels:
      com.microsoft.visualstudio.debuggee.program: "dotnet"
      #com.microsoft.visualstudio.debuggee.arguments: " $debuggee_arguments_probing_paths_sms.api$ \"/app/bin/Debug/netcoreapp3.1/SMS.API.dll\""
      com.microsoft.visualstudio.debuggee.workingdirectory: "/app"
      com.microsoft.visualstudio.debuggee.killprogram: "/bin/sh -c \"if PID=$$(pidof dotnet); then kill $$PID; fi\""
    tty: true
